//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.28 at 01:40:19 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.i2b2.org/xsd/cell/pm/1.1/")
package edu.harvard.i2b2.crc.datavo.pm;
